name: Install development tools
description: GitHub Action for installing development tools

inputs:
  tool:
    description: Tools to install (comma-separated list)
    required: true
    # default: #publish:tool
  checksum:
    description: Whether to enable checksums
    required: false
    default: 'true'

runs:
  using: node16
  main: main.js
