name: Install development tools
description: GitHub Action for installing development tools

inputs:
  tool:
    description: Tools to install (comma-separated list)
    required: true
    # default: #publish:tool
  checksum:
    description: Whether to enable checksums
    required: false
    default: 'true'
  fallback:
    description: Whether to use fallback (none or cargo-binstall)
    required: false
    default: 'cargo-binstall'

# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - Use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
      shell: bash
      env:
        INPUT_TOOL: ${{ inputs.tool }}
        INPUT_CHECKSUM: ${{ inputs.checksum }}
        INPUT_FALLBACK: ${{ inputs.fallback }}
