name: Manifest

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - ci-*
  schedule:
    - cron: '0 0,3,6,9,12,15,18,21 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  manifest:
    uses: taiki-e/github-actions/.github/workflows/gen.yml@931686d4e4cf88b13e790040727ccde2dba8ec62 # main
    permissions:
      contents: write # for creating branch for pr
      pull-requests: write # for gh pr review --approve
    secrets:
      PR_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PR_TOKEN_APP_PRIVATE_KEY }}
    with:
      script: tools/manifest.sh
      commit-script: tools/ci/manifest.sh
      title: Update manifest
      branch: update-manifest
      automerge: true
      install-cosign: true
      install-parse-changelog: true
