name: Manifest

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - ci-*
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  manifest:
    uses: taiki-e/github-actions/.github/workflows/gen.yml@04a42ca09aaeb9b6c0bce43c23fb9e13eb197d85 # 2026.9.9
    permissions:
      contents: write # for creating branch for pr
    secrets:
      PR_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PR_TOKEN_APP_PRIVATE_KEY }}
    with:
      script: tools/manifest.sh
      commit-script: tools/ci/manifest.sh
      title: Update manifest
      branch: update-manifest
      install-cosign: true
      install-parse-changelog: true
